services:
  gotify:
    image: gotify/server:latest
    container_name: Gotify
    ports:
      - 8080:80
    restart: unless-stopped
    environment:    
      GOTIFY_DEFAULTUSER_Name: 'Chilltactix'
      GOTIFY_DEFAULTUSER_PASS: 'MyLove199707'
    volumes:
      - './gotify_data:/app/data'
    # to run gotify as a dedicated user:
    # sudo chown -R 1234:1234 ./gotify_data
    # user: "1234:1234"
